(define (equal? list1 list2)
  (cond ((not (pair? list1)) (eq? list1 list2))
        ((not (pair? list2)) #f)
        ((not (eq? (car list1) (car list2))) #f)
        (else (equal? (cdr list1) (cdr list2)))))
