(define (square-tree1 tree)
  (cond ((null? tree) ())
        ((not (pair? tree)) (square tree))
        (else (cons (square-tree1 (car tree))
                    (square-tree1 (cdr tree))))))

(define (square-tree2 tree)
  (map (lambda (subtree)
         (if (pair? subtree)
             (square-tree2 subtree)
             (square subtree)))
       tree))

(define (tree-map1 proc tree)
  (cond ((null? tree) ())
        ((not (pair? tree)) (proc tree))
        (else (cons (tree-map1 proc (car tree))
                    (tree-map1 proc (cdr tree))))))

(define (tree-map2 proc tree)
  (map (lambda (subtree)
         (if (pair? subtree)
             (tree-map2 proc subtree)
             (proc subtree)))
       tree))
