(define (make-account balance secret-password)
  (let ((limit 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (incorrect amount)
      (set! limit (+ limit 1))
      (if (> limit 7)
          (call-the-police "Account Locked")
          "Incorrect password"))
    (define (call-the-police x)
      (set! secret-password 'thou-shalt-not-guess-me)
      x)
    (define (dispatch password m)
      (cond ((not (eq? password secret-password)) incorrect)
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown requests -- MAKE ACCOUNT"
                         m))))
    dispatch))
